### ISSUE TITLE
nginx-proxy assumes that nginx-storage always works over plain HTTP

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent-deployment#81]
The current configuration for `nginx-proxy` and `nginx-storage` on the same cluster looks like this:
```
location ~ ^/(download|upload)/ {
        set $nginx_storage_backend http://nginx-storage.default.svc.cluster.local;
        client_max_body_size               {{ max_upload_size }};
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $remote_addr;
        proxy_set_header Host              $http_host;
        proxy_pass                         $nginx_storage_backend;
    }
```

Note that the address has `http://` hard-coded. This means that it won't work when we disable HTTP on `nginx-storage`.

We could set it to `http` or `https` conditionally but the problem is that in this setup we'd have to have a special certificate for the local domain name used here (`nginx-storage.default.svc.cluster.local`) and not the external domain that we normally use.

**Comment by cameel** [comment]
I'm not sure what the solution will be. The current code works on a single cluster as long as we don't have HTTPS enabled on `nginx-storage` (and we don't need it on a single cluster because HTTPS in `nginx-proxy` covers that) and will work fine when we move on to separate clusters with HTTPS enabled.

Maybe we should just add a check that fails when we try to enable HTTPS on both instances and remove the check when we set up multiple clusters.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159990884
